# Generated by Django 5.2.17 on 2026-08-11 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_tenant_foundation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
