# Generated by Django 5.2.17 on 2026-08-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_organizationinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='campaign_retention_days',
            field=models.PositiveIntegerField(default=2, help_text='Days before patient name and phone are removed from a finished list. Set 0 to keep them indefinitely.'),
        ),
    ]
