# Generated by Django 5.2.17 on 2026-08-11 04:31

import django.db.models.deletion
from django.db import migrations, models


def backfill_import_issues(apps, schema_editor):
    ImportIssue = apps.get_model("imports", "ImportIssue")
    ImportBatch = apps.get_model("rasel", "ImportBatch")
    issues = []
    for batch in ImportBatch.objects.exclude(errors=[]).iterator():
        for issue in batch.errors or []:
            issues.append(
                ImportIssue(
                    organization_id=batch.organization_id,
                    batch_id=batch.pk,
                    row_number=issue.get("row"),
                    column=issue.get("column", ""),
                    code=issue.get("code", ""),
                    message=issue.get("message", "Import failed")[:1000],
                )
            )
    ImportIssue.objects.bulk_create(issues, batch_size=500)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_tenant_foundation'),
        ('rasel', '0005_remove_contact_unique_contact_mrn_per_org_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_number', models.PositiveIntegerField(blank=True, null=True)),
                ('column', models.CharField(blank=True, max_length=255)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('message', models.CharField(max_length=1000)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='rasel.importbatch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.organization')),
            ],
            options={
                'ordering': ('row_number', 'id'),
                'indexes': [models.Index(fields=['organization', 'batch', 'row_number'], name='import_issue_lookup_idx')],
            },
        ),
        migrations.RunPython(
            backfill_import_issues,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
