# Generated by Django 5.2.17 on 2026-08-11 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_tenant_foundation'),
        ('imports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(choices=[('appointment', 'Appointment reminders'), ('marketing', 'Marketing')], max_length=20)),
                ('original_filename', models.CharField(max_length=255)),
                ('source_file', models.FileField(blank=True, upload_to='imports/%Y/%m/')),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('validated', 'Validated'), ('imported', 'Imported'), ('failed', 'Failed'), ('replaced', 'Replaced')], default='uploaded', max_length=20)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('imported_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.organization')),
                ('replaces', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement', to='imports.importbatch')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rasel_importbatch',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterField(
            model_name='importissue',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='imports.importbatch'),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['organization', 'purpose', 'status'], name='import_org_purpose_idx'),
        ),
            ],
        ),
    ]
