# Generated by Django 5.2.17 on 2026-08-11 04:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_delete_userprofile'),
        ('imports', '0002_importbatch_alter_importissue_batch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.CheckConstraint(condition=models.Q(('purpose__in', ('appointment', 'marketing'))), name='valid_import_purpose'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('uploaded', 'validated', 'imported', 'failed', 'replaced'))), name='valid_import_status'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.CheckConstraint(condition=models.Q(('imported_count__lte', models.F('row_count'))), name='imported_not_above_rows'),
        ),
    ]
