# Generated by Django 5.2.17 on 2026-08-11 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0003_importbatch_valid_import_purpose_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importbatch',
            name='source_file',
        ),
    ]
