# Generated by Django 5.2.17 on 2026-09-03 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_campaign_cancellation_template_and_more'),
        ('imports', '0004_remove_importbatch_source_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='updates_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_batches', to='campaigns.campaign'),
        ),
    ]
