# Generated by Django 5.2.17 on 2026-08-11 04:14

import datetime
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def backfill_appointments(apps, schema_editor):
    Appointment = apps.get_model("appointments", "Appointment")
    AppointmentStatusEvent = apps.get_model(
        "appointments", "AppointmentStatusEvent"
    )
    CampaignItem = apps.get_model("rasel", "CampaignItem")

    items = CampaignItem.objects.filter(
        campaign__purpose="appointment",
        appointment_date__isnull=False,
        appointment_time__isnull=False,
    ).select_related("campaign__created_by", "organization")
    for item in items.iterator():
        naive_value = datetime.datetime.combine(
            item.appointment_date, item.appointment_time
        )
        try:
            organization_timezone = ZoneInfo(item.organization.timezone)
        except ZoneInfoNotFoundError:
            organization_timezone = datetime.timezone.utc
        scheduled_at = timezone.make_aware(naive_value, organization_timezone)
        appointment = Appointment.objects.create(
            organization_id=item.organization_id,
            contact_id=item.contact_id,
            doctor_id=item.doctor_id,
            source_import_id=item.campaign.import_batch_id,
            scheduled_at=scheduled_at,
            status=item.appointment_status or "booked",
            remarks=item.appointment_remarks or "",
        )
        AppointmentStatusEvent.objects.create(
            organization_id=item.organization_id,
            appointment_id=appointment.pk,
            previous_status="",
            new_status=appointment.status,
            changed_by_id=item.campaign.created_by_id,
            reason="Backfilled from an existing campaign item.",
        )
        item.appointment_id = appointment.pk
        item.save(update_fields=("appointment",))


def remove_backfilled_appointments(apps, schema_editor):
    Appointment = apps.get_model("appointments", "Appointment")
    CampaignItem = apps.get_model("rasel", "CampaignItem")
    appointment_ids = list(
        CampaignItem.objects.filter(appointment__isnull=False).values_list(
            "appointment_id", flat=True
        )
    )
    CampaignItem.objects.filter(appointment__isnull=False).update(appointment=None)
    Appointment.objects.filter(pk__in=appointment_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('rasel', '0002_tenant_campaign_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignitem',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaign_items', to='appointments.appointment'),
        ),
        migrations.RunPython(
            backfill_appointments, reverse_code=remove_backfilled_appointments
        ),
    ]
