# Generated by Django 5.2.17 on 2026-08-11 04:21

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def create_initial_template_revisions(apps, schema_editor):
    Campaign = apps.get_model("rasel", "Campaign")
    CampaignMessage = apps.get_model("rasel", "CampaignMessage")
    MessageTemplate = apps.get_model("rasel", "MessageTemplate")
    MessageTemplateRevision = apps.get_model(
        "messaging", "MessageTemplateRevision"
    )

    for template in MessageTemplate.objects.all().iterator():
        approved_at = template.approved_at
        approved_by_id = template.approved_by_id
        if template.approval_status == "approved":
            approved_at = approved_at or template.updated_at or timezone.now()
            approved_by_id = approved_by_id or template.created_by_id
        revision = MessageTemplateRevision.objects.create(
            organization_id=template.organization_id,
            template_id=template.pk,
            version=1,
            content=template.content,
            approval_status=template.approval_status,
            created_by_id=template.created_by_id,
            approved_by_id=approved_by_id,
            approved_at=approved_at,
            is_current=True,
        )
        template.current_revision_id = revision.pk
        template.save(update_fields=("current_revision",))
        Campaign.objects.filter(template_id=template.pk).update(
            template_revision_id=revision.pk
        )
        CampaignMessage.objects.filter(template_id=template.pk).update(
            template_revision_id=revision.pk
        )

    CampaignMessage.objects.filter(status="sent").update(
        status="operator_marked_sent"
    )


def remove_initial_template_revisions(apps, schema_editor):
    Campaign = apps.get_model("rasel", "Campaign")
    CampaignMessage = apps.get_model("rasel", "CampaignMessage")
    MessageTemplate = apps.get_model("rasel", "MessageTemplate")
    MessageTemplateRevision = apps.get_model(
        "messaging", "MessageTemplateRevision"
    )

    CampaignMessage.objects.filter(status="operator_marked_sent").update(
        status="sent"
    )
    Campaign.objects.update(template_revision=None)
    CampaignMessage.objects.update(template_revision=None)
    MessageTemplate.objects.update(current_revision=None)
    MessageTemplateRevision.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        ('rasel', '0003_campaignitem_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='template_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='messaging.messagetemplaterevision'),
        ),
        migrations.AddField(
            model_name='campaignmessage',
            name='template_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendered_messages', to='messaging.messagetemplaterevision'),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_templates', to='messaging.messagetemplaterevision'),
        ),
        migrations.RunPython(
            create_initial_template_revisions,
            reverse_code=remove_initial_template_revisions,
        ),
        migrations.AlterField(
            model_name='campaignmessage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('opened', 'WhatsApp opened'), ('operator_marked_sent', 'Operator marked sent'), ('skipped', 'Skipped')], default='pending', max_length=30),
        ),
    ]
