# Generated by Django 5.2.17 on 2026-08-11 04:28

import unicodedata

from django.db import migrations, models


def canonical_key(value):
    if value is None:
        return ""
    display_value = " ".join(unicodedata.normalize("NFKC", str(value)).split())
    return display_value.casefold()


def unique_legacy_key(
    model,
    *,
    organization_id,
    field_name,
    value,
    pk,
    max_length,
    allow_blank=True,
):
    candidate = canonical_key(value)
    if not candidate:
        return "" if allow_blank else f"legacy-{pk}"
    if not model.objects.filter(
        organization_id=organization_id,
        **{field_name: candidate},
    ).exclude(pk=pk).exists():
        return candidate
    suffix = f"~legacy-{pk}"
    return f"{candidate[:max_length - len(suffix)]}{suffix}"


def populate_normalized_directory_fields(apps, schema_editor):
    Contact = apps.get_model("rasel", "Contact")
    Department = apps.get_model("rasel", "Department")
    Doctor = apps.get_model("rasel", "Doctor")

    for contact in Contact.objects.all().order_by("pk").iterator():
        contact.normalized_mrn = unique_legacy_key(
            Contact,
            organization_id=contact.organization_id,
            field_name="normalized_mrn",
            value=contact.mrn,
            pk=contact.pk,
            max_length=230,
        )
        contact.save(update_fields=("normalized_mrn",))
    for department in Department.objects.all().order_by("pk").iterator():
        department.normalized_name = unique_legacy_key(
            Department,
            organization_id=department.organization_id,
            field_name="normalized_name",
            value=department.name,
            pk=department.pk,
            max_length=150,
            allow_blank=False,
        )
        department.save(update_fields=("normalized_name",))
    for doctor in Doctor.objects.all().order_by("pk").iterator():
        doctor.normalized_name = canonical_key(doctor.name)
        doctor.normalized_code = unique_legacy_key(
            Doctor,
            organization_id=doctor.organization_id,
            field_name="normalized_code",
            value=doctor.code,
            pk=doctor.pk,
            max_length=100,
        )
        doctor.save(update_fields=("normalized_name", "normalized_code"))


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_tenant_foundation'),
        ('rasel', '0004_campaign_template_revision_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contact',
            name='unique_contact_mrn_per_org',
        ),
        migrations.RemoveConstraint(
            model_name='department',
            name='unique_department_name_per_org',
        ),
        migrations.RemoveConstraint(
            model_name='doctor',
            name='unique_doctor_code_per_org',
        ),
        migrations.RemoveIndex(
            model_name='contact',
            name='contact_org_mrn_idx',
        ),
        migrations.RemoveIndex(
            model_name='doctor',
            name='doctor_org_name_idx',
        ),
        migrations.AddField(
            model_name='contact',
            name='normalized_mrn',
            field=models.CharField(blank=True, default='', editable=False, max_length=230),
        ),
        migrations.AddField(
            model_name='department',
            name='normalized_name',
            field=models.CharField(default='', editable=False, max_length=150),
        ),
        migrations.AddField(
            model_name='doctor',
            name='normalized_code',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='normalized_name',
            field=models.CharField(default='', editable=False, max_length=230),
        ),
        migrations.RunPython(
            populate_normalized_directory_fields,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['organization', 'normalized_mrn'], name='contact_org_mrn_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['organization', 'normalized_name', 'department'], name='doctor_org_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(condition=models.Q(('normalized_mrn', ''), _negated=True), fields=('organization', 'normalized_mrn'), name='unique_contact_mrn_per_org'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('organization', 'normalized_name'), name='unique_department_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='doctor',
            constraint=models.UniqueConstraint(condition=models.Q(('normalized_code', ''), _negated=True), fields=('organization', 'normalized_code'), name='unique_doctor_code_per_org'),
        ),
    ]
