# Generated by Django 5.2.17 on 2026-08-11 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_contact_alter_appointment_doctor'),
        ('directory', '0001_initial'),
        ('rasel', '0005_remove_contact_unique_contact_mrn_per_org_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.AlterField(
            model_name='campaignitem',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_items', to='directory.contact'),
        ),
        migrations.RemoveField(
            model_name='department',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='department',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='organization',
        ),
        migrations.AlterField(
            model_name='doctorsummary',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='summaries', to='directory.doctor'),
        ),
        migrations.AlterField(
            model_name='campaignitem',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaign_items', to='directory.doctor'),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
            ],
        ),
    ]
