# Generated by Django 5.2.17 on 2026-08-11 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_campaignmessage_alter_messagehandoffevent_message_and_more'),
        ('rasel', '0006_alter_campaignitem_contact_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.RemoveField(
            model_name='messagetemplate',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='messagetemplate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='messagetemplate',
            name='current_revision',
        ),
        migrations.RemoveField(
            model_name='messagetemplate',
            name='organization',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='messaging.messagetemplate'),
        ),
        migrations.DeleteModel(
            name='CampaignMessage',
        ),
        migrations.DeleteModel(
            name='MessageTemplate',
        ),
            ],
        ),
    ]
