# Generated by Django 5.2.17 on 2026-08-11 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_source_import'),
        ('imports', '0002_importbatch_alter_importissue_batch_and_more'),
        ('rasel', '0007_remove_messagetemplate_approved_by_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.AlterField(
            model_name='campaign',
            name='import_batch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaign', to='imports.importbatch'),
        ),
        migrations.DeleteModel(
            name='ImportBatch',
        ),
            ],
        ),
    ]
