# Generated by Django 5.2.17 on 2026-08-11 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_alter_campaignmessage_campaign_item'),
        ('rasel', '0008_alter_campaign_import_batch_delete_importbatch'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.RemoveField(
            model_name='doctorsummary',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='campaignitem',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='campaignitem',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='campaignitem',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='campaignitem',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='campaignitem',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='doctorsummary',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='doctorsummary',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='doctorsummary',
            name='sent_by',
        ),
        migrations.DeleteModel(
            name='Campaign',
        ),
        migrations.DeleteModel(
            name='CampaignItem',
        ),
        migrations.DeleteModel(
            name='DoctorSummary',
        ),
            ],
        ),
    ]
