# Generated by Django 5.2.17 on 2026-08-11 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_tenant_foundation'),
        ('rasel', '0003_campaignitem_appointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageHandoffEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('content_edited', 'Content edited'), ('whatsapp_opened', 'WhatsApp opened'), ('status_changed', 'Status changed')], max_length=30)),
                ('previous_status', models.CharField(blank=True, max_length=30)),
                ('new_status', models.CharField(blank=True, max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message_handoff_events', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handoff_events', to='rasel.campaignmessage')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.organization')),
            ],
            options={
                'ordering': ('created_at', 'id'),
                'indexes': [models.Index(fields=['organization', 'created_at'], name='handoff_org_created_idx'), models.Index(fields=['message', 'created_at'], name='handoff_message_idx')],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplateRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('approval_status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=500)),
                ('is_current', models.BooleanField(default=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_template_revisions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_template_revisions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.organization')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='rasel.messagetemplate')),
            ],
            options={
                'ordering': ('template', '-version'),
                'indexes': [models.Index(fields=['organization', 'approval_status'], name='revision_org_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('template', 'version'), name='unique_template_revision'), models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('template',), name='unique_current_template_revision')],
            },
        ),
    ]
