# Generated by Django 5.2.17 on 2026-08-11 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_tenant_foundation'),
        ('messaging', '0001_initial'),
        ('rasel', '0006_alter_campaignitem_contact_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.CreateModel(
            name='CampaignMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rendered_content', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('opened', 'WhatsApp opened'), ('operator_marked_sent', 'Operator marked sent'), ('skipped', 'Skipped')], default='pending', max_length=30)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('campaign_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='rasel.campaignitem')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.organization')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_campaign_messages', to=settings.AUTH_USER_MODEL)),
                ('template_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendered_messages', to='messaging.messagetemplaterevision')),
            ],
            options={
                'db_table': 'rasel_campaignmessage',
            },
        ),
        migrations.AlterField(
            model_name='messagehandoffevent',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handoff_events', to='messaging.campaignmessage'),
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('purpose', models.CharField(choices=[('appointment', 'Appointment reminder'), ('marketing', 'Marketing'), ('general', 'General')], default='appointment', max_length=20)),
                ('content', models.TextField()),
                ('approval_status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_message_templates', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_message_templates', to=settings.AUTH_USER_MODEL)),
                ('current_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_templates', to='messaging.messagetemplaterevision')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.organization')),
            ],
            options={
                'db_table': 'rasel_messagetemplate',
                'ordering': ('name',),
                'permissions': [('approve_messagetemplate', 'Can approve message templates')],
            },
        ),
        migrations.AddField(
            model_name='campaignmessage',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendered_messages', to='messaging.messagetemplate'),
        ),
        migrations.AlterField(
            model_name='messagetemplaterevision',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='messaging.messagetemplate'),
        ),
        migrations.AddConstraint(
            model_name='messagetemplate',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_template_name_per_org'),
        ),
        migrations.AddIndex(
            model_name='campaignmessage',
            index=models.Index(fields=['organization', 'status'], name='message_org_status_idx'),
        ),
            ],
        ),
    ]
