# Generated by Django 5.2.17 on 2026-08-11 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('messaging', '0002_campaignmessage_alter_messagehandoffevent_message_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.AlterField(
            model_name='campaignmessage',
            name='campaign_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='campaigns.campaignitem'),
        ),
            ],
        ),
    ]
