# Generated by Django 5.2.17 on 2026-08-11 04:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_delete_userprofile'),
        ('campaigns', '0002_campaign_valid_campaign_purpose_and_more'),
        ('messaging', '0003_alter_campaignmessage_campaign_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='campaignmessage',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('pending', 'opened', 'operator_marked_sent', 'skipped'))), name='valid_campaign_message_status'),
        ),
        migrations.AddConstraint(
            model_name='messagetemplate',
            constraint=models.CheckConstraint(condition=models.Q(('purpose__in', ('appointment', 'marketing', 'general'))), name='valid_template_purpose'),
        ),
        migrations.AddConstraint(
            model_name='messagetemplate',
            constraint=models.CheckConstraint(condition=models.Q(('approval_status__in', ('draft', 'pending', 'approved', 'rejected'))), name='valid_template_approval'),
        ),
        migrations.AddConstraint(
            model_name='messagetemplaterevision',
            constraint=models.CheckConstraint(condition=models.Q(('approval_status__in', ('draft', 'pending', 'approved', 'rejected'))), name='valid_revision_approval'),
        ),
    ]
