# Generated by Django 5.2.17 on 2026-09-03 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_organization_campaign_retention_days'),
        ('campaigns', '0005_campaign_cancellation_template_and_more'),
        ('messaging', '0004_campaignmessage_valid_campaign_message_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='campaignmessage',
            name='valid_campaign_message_status',
        ),
        migrations.AddField(
            model_name='campaignmessage',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignmessage',
            name='stage',
            field=models.CharField(choices=[('reminder', 'Reminder'), ('follow_up', '24-hour follow-up'), ('cancellation', 'Cancellation')], default='reminder', max_length=20),
        ),
        migrations.AlterField(
            model_name='campaignmessage',
            name='campaign_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='campaigns.campaignitem'),
        ),
        migrations.AlterField(
            model_name='campaignmessage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('opened', 'WhatsApp opened'), ('operator_marked_sent', 'Operator marked sent'), ('skipped', 'Skipped'), ('voided', 'No longer needed')], default='pending', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='campaignmessage',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('pending', 'opened', 'operator_marked_sent', 'skipped', 'voided'))), name='valid_campaign_message_status'),
        ),
        migrations.AddConstraint(
            model_name='campaignmessage',
            constraint=models.CheckConstraint(condition=models.Q(('stage__in', ('reminder', 'follow_up', 'cancellation'))), name='valid_campaign_message_stage'),
        ),
        migrations.AddConstraint(
            model_name='campaignmessage',
            constraint=models.UniqueConstraint(fields=('campaign_item', 'stage'), name='unique_message_stage_per_item'),
        ),
    ]
