# Generated by Django 5.2.17 on 2026-08-11 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_contact_alter_appointment_doctor'),
        ('imports', '0002_importbatch_alter_importissue_batch_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.AlterField(
            model_name='appointment',
            name='source_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='imports.importbatch'),
        ),
            ],
        ),
    ]
