# Generated by Django 5.2.17 on 2026-08-11 04:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_delete_userprofile'),
        ('appointments', '0003_alter_appointment_source_import'),
        ('directory', '0001_initial'),
        ('imports', '0002_importbatch_alter_importissue_batch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('booked', 'confirmed', 'cancelled'))), name='valid_appointment_status'),
        ),
        migrations.AddConstraint(
            model_name='appointmentstatusevent',
            constraint=models.CheckConstraint(condition=models.Q(('previous_status', ''), ('previous_status__in', ['booked', 'confirmed', 'cancelled']), _connector='OR'), name='valid_previous_appt_status'),
        ),
        migrations.AddConstraint(
            model_name='appointmentstatusevent',
            constraint=models.CheckConstraint(condition=models.Q(('new_status__in', ['booked', 'confirmed', 'cancelled'])), name='valid_new_appt_status'),
        ),
    ]
