# Generated by Django 5.2.17 on 2026-08-11 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_tenant_foundation'),
        ('appointments', '0003_alter_appointment_source_import'),
        ('directory', '0001_initial'),
        ('imports', '0002_importbatch_alter_importissue_batch_and_more'),
        ('messaging', '0002_campaignmessage_alter_messagehandoffevent_message_and_more'),
        ('rasel', '0008_alter_campaign_import_batch_delete_importbatch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=230)),
                ('purpose', models.CharField(choices=[('appointment', 'Appointment reminders'), ('marketing', 'Marketing')], default='appointment', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
                ('import_batch', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaign', to='imports.importbatch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.organization')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='messaging.messagetemplate')),
                ('template_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='messaging.messagetemplaterevision')),
            ],
            options={
                'db_table': 'rasel_campaign',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CampaignItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_number', models.PositiveIntegerField(default=1)),
                ('patient_name_snapshot', models.CharField(max_length=230)),
                ('phone_number_snapshot', models.CharField(max_length=20)),
                ('mrn_snapshot', models.CharField(blank=True, max_length=230)),
                ('doctor_name_snapshot', models.CharField(blank=True, max_length=230)),
                ('department_name_snapshot', models.CharField(blank=True, max_length=150)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('appointment_time', models.TimeField(blank=True, null=True)),
                ('appointment_remarks', models.CharField(blank=True, max_length=500)),
                ('appointment_status', models.CharField(blank=True, choices=[('booked', 'Booked'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], max_length=20, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaign_items', to='appointments.appointment')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='campaigns.campaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_items', to='directory.contact')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaign_items', to='directory.doctor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.organization')),
            ],
            options={
                'db_table': 'rasel_campaignitem',
                'ordering': ('row_number', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DoctorSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rendered_content', models.TextField()),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('opened', 'WhatsApp opened'), ('sent', 'Marked sent')], default='draft', max_length=10)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_summaries', to='campaigns.campaign')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='summaries', to='directory.doctor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.organization')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_doctor_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rasel_doctorsummary',
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['organization', 'purpose', 'status'], name='campaign_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['organization', 'created_at'], name='campaign_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignitem',
            index=models.Index(fields=['organization', 'appointment_date'], name='item_org_date_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignitem',
            index=models.Index(fields=['organization', 'appointment_status'], name='item_org_appt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignitem',
            index=models.Index(fields=['organization', 'doctor_name_snapshot'], name='item_org_doctor_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignitem',
            index=models.Index(fields=['organization', 'phone_number_snapshot'], name='item_org_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignitem',
            index=models.Index(fields=['organization', 'mrn_snapshot'], name='item_org_mrn_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaignitem',
            constraint=models.UniqueConstraint(fields=('campaign', 'row_number'), name='unique_campaign_row'),
        ),
        migrations.AddConstraint(
            model_name='doctorsummary',
            constraint=models.UniqueConstraint(fields=('campaign', 'doctor'), name='unique_doctor_summary'),
        ),
            ],
        ),
    ]
