# Generated by Django 5.2.17 on 2026-08-11 04:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_delete_userprofile'),
        ('appointments', '0004_appointment_valid_appointment_status_and_more'),
        ('campaigns', '0001_initial'),
        ('directory', '0001_initial'),
        ('imports', '0002_importbatch_alter_importissue_batch_and_more'),
        ('messaging', '0003_alter_campaignmessage_campaign_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(condition=models.Q(('purpose__in', ('appointment', 'marketing'))), name='valid_campaign_purpose'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('draft', 'ready', 'active', 'completed', 'archived'))), name='valid_campaign_status'),
        ),
        migrations.AddConstraint(
            model_name='campaignitem',
            constraint=models.CheckConstraint(condition=models.Q(('appointment_status__isnull', True), ('appointment_status__in', ('booked', 'confirmed', 'cancelled')), _connector='OR'), name='valid_campaign_appt_status'),
        ),
        migrations.AddConstraint(
            model_name='doctorsummary',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('draft', 'opened', 'sent'))), name='valid_doctor_summary_status'),
        ),
    ]
