# Generated by Django 5.2.17 on 2026-08-11 04:58

from django.conf import settings
from django.db import migrations, models


def make_sent_status_explicit(apps, schema_editor):
    DoctorSummary = apps.get_model("campaigns", "DoctorSummary")
    DoctorSummary.objects.filter(status="sent").update(
        status="operator_marked_sent"
    )


def restore_legacy_sent_status(apps, schema_editor):
    DoctorSummary = apps.get_model("campaigns", "DoctorSummary")
    DoctorSummary.objects.filter(status="operator_marked_sent").update(status="sent")


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_delete_userprofile'),
        ('campaigns', '0002_campaign_valid_campaign_purpose_and_more'),
        ('directory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='doctorsummary',
            name='valid_doctor_summary_status',
        ),
        migrations.AlterField(
            model_name='doctorsummary',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('opened', 'WhatsApp opened'), ('operator_marked_sent', 'Operator marked sent')], default='draft', max_length=30),
        ),
        migrations.RunPython(
            make_sent_status_explicit,
            reverse_code=restore_legacy_sent_status,
        ),
        migrations.AddConstraint(
            model_name='doctorsummary',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('draft', 'opened', 'operator_marked_sent'))), name='valid_doctor_summary_status'),
        ),
    ]
