# Generated by Django 5.2.17 on 2026-08-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_remove_doctorsummary_valid_doctor_summary_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='scrub_after',
            field=models.DateTimeField(blank=True, help_text='When patient name and phone are removed from this list. Empty means they are kept indefinitely.', null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='scrubbed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
