# Generated by Django 5.2.17 on 2026-09-03 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaign_scrub_after_campaign_scrubbed_at'),
        ('messaging', '0004_campaignmessage_valid_campaign_message_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='cancellation_template',
            field=models.ForeignKey(blank=True, help_text='Raised at 19:00 the evening before when no confirmation has arrived. Leave empty to skip that stage.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancellation_campaigns', to='messaging.messagetemplate'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='follow_up_template',
            field=models.ForeignKey(blank=True, help_text='Sent 24 hours before the appointment. Leave empty to skip that stage.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='follow_up_campaigns', to='messaging.messagetemplate'),
        ),
    ]
