# Generated by Django 5.2.17 on 2026-08-11 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_tenant_foundation'),
        ('rasel', '0005_remove_contact_unique_contact_mrn_per_org_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('normalized_name', models.CharField(default='', editable=False, max_length=150)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.organization')),
            ],
            options={
                'db_table': 'rasel_department',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=230)),
                ('normalized_name', models.CharField(default='', editable=False, max_length=230)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('normalized_code', models.CharField(blank=True, editable=False, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='directory.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.organization')),
            ],
            options={
                'db_table': 'rasel_doctor',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=230)),
                ('phone_number', models.CharField(max_length=20)),
                ('mrn', models.CharField(blank=True, max_length=230, null=True)),
                ('normalized_mrn', models.CharField(blank=True, default='', editable=False, max_length=230)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.organization')),
            ],
            options={
                'db_table': 'rasel_contact',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['organization', 'name'], name='contact_org_name_idx'), models.Index(fields=['organization', 'normalized_mrn'], name='contact_org_mrn_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'phone_number'), name='unique_contact_phone_per_org'), models.UniqueConstraint(condition=models.Q(('normalized_mrn', ''), _negated=True), fields=('organization', 'normalized_mrn'), name='unique_contact_mrn_per_org')],
            },
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('organization', 'normalized_name'), name='unique_department_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('organization', 'code'), name='unique_department_code_per_org'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['organization', 'normalized_name', 'department'], name='doctor_org_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='doctor',
            constraint=models.UniqueConstraint(condition=models.Q(('normalized_code', ''), _negated=True), fields=('organization', 'normalized_code'), name='unique_doctor_code_per_org'),
        ),
            ],
        ),
    ]
