# Generated by Django 5.2.17 on 2026-08-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_organization_campaign_retention_days'),
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contact',
            name='unique_contact_phone_per_org',
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(condition=models.Q(('normalized_mrn', '')), fields=('organization', 'phone_number'), name='unique_contact_phone_without_mrn_per_org'),
        ),
    ]
